"""
THIS SCRIPT SETS UP THE MYSQL DATABASE AND TABLES FOR THE ALGOTRADER APPLICATION.
IT CONNECTS TO THE MYSQL SERVER USING CREDENTIALS FROM YOUR CREDENTIALS.ENV FILE, CREATES THE DATABASE IF IT DOESN'T EXIST,
AND CREATES THE NECESSARY TABLES FOR STORING TRADES, ERRORS, AND EVENTS.
RUN ONCE TO INITIALIZE THE DATABASE.
"""

import mysql.connector as my
import os
from dotenv import load_dotenv

load_dotenv("credentials.env")
USERNAME = os.getenv("DATABASE_USERNAME")
PASSWORD = os.getenv("DATABASE_PASSWORD")
HOST = os.getenv("DATABASE_HOST")

conn = my.connect(host=HOST, user=USERNAME, password=PASSWORD)

if conn.is_connected():
    print("Connected to MySQL database")
else:
    print("Failed to connect to MySQL database")

cursor = conn.cursor()
cursor.execute("CREATE DATABASE IF NOT EXISTS ALGOTRADER")
cursor.execute("USE ALGOTRADER")
cursor.execute("""CREATE TABLE IF NOT EXISTS TRADES (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    TIMESTAMP TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    TICKER VARCHAR(10) NOT NULL,
    SIDE ENUM('buy', 'sell') NOT NULL,
    QUANTITY FLOAT NOT NULL,
    PRICE FLOAT NOT NULL,
    TOTAL FLOAT NOT NULL,
    PORTFOLIO FLOAT NOT NULL,
    INDEX idx_ticker (TICKER),
    INDEX idx_timestamp (TIMESTAMP),
    INDEX idx_side (SIDE)
)""")
conn.commit()
cursor.execute("""CREATE TABLE IF NOT EXISTS PORTFOLIO_STATE (
    ID TINYINT PRIMARY KEY,
    CAPITAL FLOAT NOT NULL,
    PORTFOLIO FLOAT NOT NULL,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
)""")
conn.commit()
cursor.execute("""INSERT INTO PORTFOLIO_STATE (ID, CAPITAL, PORTFOLIO)
VALUES (1, 100000.0, 100000.0)
ON DUPLICATE KEY UPDATE ID = ID""")
conn.commit()
cursor.execute("""CREATE TABLE IF NOT EXISTS HOLDINGS (
    TICKER VARCHAR(10) PRIMARY KEY,
    QUANTITY FLOAT NOT NULL DEFAULT 0,
    PURCHASE_PRICE FLOAT NOT NULL DEFAULT 0,
    BUY_TIMESTAMP DATETIME NULL,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
)""")
conn.commit()
cursor.execute("""CREATE TABLE IF NOT EXISTS ERRORS (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    TIMESTAMP TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    TYPE VARCHAR(10) DEFAULT 'ERROR',
    MESSAGE TEXT NOT NULL
)""")
conn.commit()
cursor.execute("""CREATE TABLE IF NOT EXISTS EVENTS (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    TIMESTAMP TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    TYPE VARCHAR(10) DEFAULT 'EVENT',
    MESSAGE TEXT NOT NULL
)""")
print("Database and table setup completed.")
conn.commit()
cursor.close()
conn.close()

print("MySQL connection closed.")
